linters:
  enable-all: false
  disable-all: true
  enable:
    - unused
    - depguard
    - gocritic
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - exportloopref
    - typecheck
    - unconvert
    - unparam
run:
  tests: true
issues:
  exclude-use-default: false
  exclude:
    - "should have comment(.*)or be unexported"
  max-same-issues: 0
  max-issues-per-linter: 0
